class SwagLabs:
    USER_NAME_PLACEHOLDER = "//input[@placeholder='Username']"
    PASSWORD_PLACEHOLDER = "//input[@placeholder='Password']"
    LOGIN_BUTTON = "//input[@ID='login-button']"
    PRODUCT_TEXT_FILES = "//span[@class='title']"
    SWAG_LABS_BAG_HEADER = ("//a[@id='item_4_title_link']/div[@class='inventory_item_name ' and contains(text(), "
                            "'Sauce Labs Backpack')]")
    ADD_TO_CART_BUTTON = "//button[@id='add-to-cart']"
    SHOPPING_CART_BUTTON = "//a[@class='shopping_cart_link']"
    YOUR_CART_PRICE_TEXT = "//div[@class='inventory_item_price']"
    CHECKOUT_BUTTON = "//button[@id='checkout']"
    CHECKOUT_FIRST_NAME = "(//div[@class='checkout_info']//div//input)[1]"
    CHECKOUT_LAST_NAME = "(//div[@class='checkout_info']//div//input)[2]"
    CHECKOUT_ZIP_CODE = "(//div[@class='checkout_info']//div//input)[3]"
    CHECKOUT_CONTINUE_BUTTON = "//input[@id='continue']"
    FINISH_BUTTON = "//BUTTON[@id='finish']"
    DISH_PATCHED_TEXT = "//div[@class='complete-text']"
